"""Fix model imports

Revision ID: ab389dce72d7
Revises: fcd974f62bbc
Create Date: 2024-09-27 01:10:22.917264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab389dce72d7'
down_revision: Union[str, None] = 'fcd974f62bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('mg_calcium', sa.Float(), nullable=True))
    op.add_column('menu_item', sa.Column('mg_potassium', sa.Float(), nullable=True))
    op.add_column('menu_item', sa.Column('mg_iron', sa.Float(), nullable=True))
    op.add_column('menu_item', sa.Column('mcg_vitamin_a', sa.Float(), nullable=True))
    op.add_column('menu_item', sa.Column('mg_vitamin_c', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'mg_vitamin_c')
    op.drop_column('menu_item', 'mcg_vitamin_a')
    op.drop_column('menu_item', 'mg_iron')
    op.drop_column('menu_item', 'mg_potassium')
    op.drop_column('menu_item', 'mg_calcium')
    # ### end Alembic commands ###
