"""change name of total fat and add serving size

Revision ID: fcd974f62bbc
Revises: 14514138a274
Create Date: 2024-09-18 20:12:31.744480

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "fcd974f62bbc"
down_revision: Union[str, None] = "14514138a274"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("menu_item", sa.Column("grams_total_fat", sa.Float(), nullable=True))
    op.add_column("menu_item", sa.Column("serving_size_oz", sa.Float(), nullable=True))
    op.drop_column("menu_item", "grams_fat")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_item",
        sa.Column(
            "grams_fat",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("menu_item", "serving_size_oz")
    op.drop_column("menu_item", "grams_total_fat")
    # ### end Alembic commands ###
