# maps the column types for tables in the hit your macros database

menu_item_type_mapping = {
    "name": "String",
    "description": "String",
    "price": "Decimal(10, 2)",
    "kcal": "Float",
    "kcal_from_fat": "Float",
    "grams_protein": "Float",
    "grams_carbs": "Float",
    "grams_dietary_fiber": "Float",
    "grams_total_sugar": "Float",
    "grams_added_sugar": "Float",
    "grams_total_fat": "Float",
    "grams_saturated_fat": "Float",
    "grams_trans_fat": "Float",
    "grams_monounsat_fat": "Float",
    "grams_polyunsat_fat": "Float",
    "mg_cholesterol": "Float",
    "mg_sodium": "Float",
    "mg_calcium": "Float",
    "mg_potassium": "Float",
    "mg_iron": "Float",
    "mcg_vitamin_a": "Float",
    "mg_vitamin_c": "Float",
    "serving_size_oz": "Float",
    "ingredients": "String",
    "allergens": "String",
    "is_breakfast": "Boolean",
    "is_dessert": "Boolean",
    "is_side_condiment": "Boolean",
    "is_add_on": "Boolean",
    "is_vegetarian": "Boolean",
    "contains_caffeine": "Boolean",
    "contains_alcohol": "Boolean",
    "contains_seafood": "Boolean",
    "is_kids_meal": "Boolean",
    "is_beverage": "Boolean",
    "is_dairy_free": "Boolean",
    "is_pescatarian": "Boolean",
    "is_vegan": "Boolean",
    "is_gluten_free": "Boolean",
    "is_keto": "Boolean",
    "created_at": "String",
    "updated_at": "String",
}
