# maps the column types for tables in the hit your macros database
from sqlalchemy import String, Float, Boolean, DECIMAL

menu_item_type_mapping = {
    "name": "object",
    "description": "object",
    "price": "float64",
    "kcal": "float64",
    "kcal_from_fat": "float64",
    "grams_protein": "float64",
    "grams_carbs": "float64",
    "grams_dietary_fiber": "float64",
    "grams_total_sugar": "float64",
    "grams_added_sugar": "float64",
    "grams_total_fat": "float64",
    "grams_saturated_fat": "float64",
    "grams_trans_fat": "float64",
    "grams_monounsat_fat": "float64",
    "grams_polyunsat_fat": "float64",
    "mg_cholesterol": "float64",
    "mg_sodium": "float64",
    "mg_calcium": "float64",
    "mg_potassium": "float64",
    "mg_iron": "float64",
    "mcg_vitamin_a": "float64",
    "mg_vitamin_c": "float64",
    "serving_size_oz": "float64",
    "ingredients": "object",
    "allergens": "object",
    "is_breakfast": "bool",
    "is_dessert": "bool",
    "is_side_condiment": "bool",
    "is_add_on": "bool",
    "is_vegetarian": "bool",
    "contains_caffeine": "bool",
    "contains_alcohol": "bool",
    "contains_seafood": "bool",
    "is_kids_meal": "bool",
    "is_beverage": "bool",
    "is_dairy_free": "bool",
    "is_pescatarian": "bool",
    "is_vegan": "bool",
    "is_gluten_free": "bool",
    "is_keto": "bool",
    "created_at": "object",  # Change to datetime64 if you need DateTime types
    "updated_at": "object",  # Change to datetime64 if you need DateTime types
}
